[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npm run seed && npm run migration:run"

[deploy]
startCommand = "node dist/apps/api/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
