[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:web"

[deploy]
startCommand = "npx serve dist/web -l $PORT -s"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
